/* The code is defining an object called `postsData` which contains four properties: `disciplinePosts`,
`productivityPosts`, `mindSetPosts`, and `masculinityPosts`. Each of these properties is an object
itself, containing posts. Each post has four properties: `date`, `title`, `img` and `id`. This code is likely 
used to store and organize data for a blog or website that features posts related to different topics. */
export const postsData = {
    disciplina: {
        post1: {
            date: '29-Agosto-23',
            title: 'Crea la Vida que Anhelas desde Hoy',
            img: 'disciplina-post1.png',
            id: '1',
            category: 'disciplina',
            content: `<p class="post-text"><span class="highlighted">"El éxito son las metas, todo lo demás son comentarios."</span> Comenzamos este artículo con una poderosa cita de Brian Tracy. Esta frase resonó profundamente en mí y me guio hacia la revelación del auténtico <span class="highlighted">propósito de mi vida</span>. Si pudiera volver a emprender mi viaje de desarrollo personal, priorizaría desde el inicio la comprensión de que las metas son la esencia misma de la existencia. En este artículo, deseo transmitirte la importancia fundamental de <span class="highlighted">establecer metas en la vida</span>. Sin unos objetivos claros y bien definidos, la vida puede carecer de sentido y valor.  Hace apenas unos meses, fui arrojado a un abismo donde esta verdad se manifestaba con claridad debido a dos motivos contundentes. Ante todo, la ignorancia me ocultó la inmensa influencia y <span class="highlighted">poder que las metas ejercen</span> y cómo podían moldear el rumbo de mi vida. En segundo término, aunque había tomado conciencia de la importancia de fijar metas, me di cuenta de que <span class="highlighted">mis objetivos carecían de la definición clara y específica</span>. Esta falta de precisión ocasionaba que mis esfuerzos se dispersaran y que no lograra canalizar de manera efectiva mis pensamientos, energía y ambiciones hacia mis metas. Este desconocimiento me llevó a perder el tiempo en actividades superfluas, actividades vagas que no me aportaban nada a mi vida, al contrario, actividades que me arruinaban como persona y que robaban mi atención, mi tiempo, mi mente, mi energía, mis pensamientos, sencillamente porque no tenía metas y no sabía que hacer, seguía hábitos del desarrollo personal solo porque me decían, pero jamás profundizaba si era mi meta, el porqué hacia esos hábitos o si quería conseguir algo en concreto con esos hábitos, literalmente estaba mejorando mi vida en piloto automático.</p> 
            <p class="post-text">¿Cómo aprendí a establecer metas y a darles mucha importancia? Viendo el seminario fénix y leyendo “Think and grow rich”, “Meditations” y “The monk who sold his ferrari”. Estos libros me expandieron la mente sobre el porqué de la vida y que venimos hacer al mundo, he sacado conclusiones brutales sobre esto, aquí te dejo una reflexión inspirada bajo una idea de Marco Aurelio que profundicé: Busca tu misión y tu propósito en la vida, pregúntate ¿para qué fuiste tu creado?, para el confort, consumismo y para disfrutar o para aportar valor y crear cosas para la sociedad. Solo te recuerdo que naces con un único propósito en la vida: servir al prójimo. Recuerda también que del mismo modo que nacemos sin absolutamente ninguna posesión material, nos vamos de este mundo sin absolutamente ninguna posesión material porque somos alma y espíritu en cuerpos humanos, no somos humanos con alma y espíritu. Y es precisamente lo que estoy haciendo, ayudarte a que cambies tu mentalidad a cambio de yo tener una buena consciencia al saber que poco o mucho, pero hice el bien a la sociedad. <span class="highlighted">Pero esto es relativo y no es una verdad absoluta</span>. Algunas personas encuentran su propósito en el servicio a los demás, mientras que otras pueden <span class="highlighted">encontrarlo en la búsqueda del conocimiento, la creatividad, el amor, la autorrealización o cosas materiales</span>. Lo que es más importante es que cada persona tenga la oportunidad de explorar su propia conexión con el mundo y descubrir lo que da significado a su existencia. Al reconocer el poder de las metas, podemos trazar un camino que nos guíe hacia la realización personal y el éxito. Escribe tus objetivos en papel o en una aplicación de notas digitales, haciendo esto el subconsciente priorizará estos pensamientos sobre los miles más de pensamientos que tengas durante el día. Dirige todas las energías cognitivas hacia tus objetivos; esto obliga a la mente a separar la paja del trigo, priorizando lo que importa. Titanes como Henry Ford, Andrew Carnegie, Elon Musk, Bill Gates y Steve Jobs no perdieron el tiempo; sus mentes se hicieron eco de un propósito, una obligación a cumplir.</p>
            <p class= "post-text" ><span class="highlighted">Cada uno de nosotros tiene un propósito único en esta vida</span>. Encontrar ese propósito es fundamental para establecer objetivos significativos. Reflexiona sobre tus talentos, pasiones y valores. ¿Cómo puedes contribuir al mundo de manera significativa? Definir tu propósito te ayudará a establecer metas alineadas con tu verdadera esencia. Una de las razones por las que estamos en este mundo es para servir a los demás. Los objetivos pueden incluir cómo impactar positivamente en la vida de quienes te rodean. Ya sea a través de la ayuda a la comunidad o el apoyo a seres queridos, establecer metas orientadas al servicio puede dar un significado más profundo a tus logros. En una sociedad impulsada por lo material, es crucial recordar que somos más que nuestras posesiones. El éxito no es un evento aislado, sino una serie de metas logradas en el camino. Cada objetivo alcanzado nos acerca más a nuestra visión de éxito. Esto nos motiva a continuar avanzando y nos ayuda a medir nuestro progreso. Recuerda, eres capaz de lograr grandes cosas cuando te comprometes con tus objetivos y te <span class="highlighted">esfuerzas por hacerlos realidad</span>. Sin obstáculos no hay metas.</p>
            <p class= "post-text" >Contempla a las personas sin rumbo, agobiadas por la agonía silenciosa de no alcanzar nunca las estrellas. A medida que las arenas del tiempo se filtran entre sus dedos, son testigos de la erosión del potencial, el despilfarro de momentos preciosos que se transforman en los fantasmas inquietantes de lo que <span class="highlighted">podrían haber sido</span >. Imagina el mundo que atraviesan, contaminado por la plaga de la indecisión, el contagio de la mediocridad. Sin estrellas que los guíen, vagan entre los escombros de oportunidades no aprovechadas, convertidos en meros espectadores de la grandeza del teatro de la vida. El tapiz de sus días está pintado con matices de melancolía, pinceladas de oportunidades perdidas y matices de una vida a medias y preocupaciones, ve como desperdician su vida en inmundicias. La agonía se intensifica cuando ven a sus compañeros ascender a las cimas del éxito. Un coro implacable de 'qué pasaría si' resuena dentro de sus mentes, ahogando la sinfonía de logros que otros disfrutan. Las punzadas de la envidia y el resentimiento arañan sus almas, un ciclo implacable que desemboca en un abismo de amargura. <span class="highlighted">¿Y qué hay de su legado?</span> En el paso del tiempo, sus nombres se desvanecen en la oscuridad, perdidos en medio de los ecos triunfantes de aquellos que se atrevieron a forjar su camino, sus vidas se vuelven intrascendentes. Este, querido lector, es el sombrío panorama que se presenta cuando la brújula del propósito permanece descalibrada. El dolor de tal existencia es un veneno que corroe el alma, un cáncer que devora el espíritu. Es una sinfonía de la desesperación, una miseria que aumenta cada día que pasa. Capta la gravedad de esta narración. El dolor, la angustia, la miseria de una vida sin propósito: este es el tapiz que se teje al descuidar el faro de las metas. Que estas palabras sirvan como un penetrante recordatorio del abismo que acecha cuando las velas del propósito permanecen enrolladas.</p>
            <p class= "post-text" >De las metas derivan herramientas muy importantes que puedes usar para lograrlas, algunas de ellas son: <span class="highlighted">la mentalidad, la disciplina, la productividad, los pensamientos, leyes mentales, la concentración y atención</span>, entre muchas más y es precisamente lo que haremos en este blog, queremos que estés consciente de esas herramientas y que las adaptes a tu vida de acuerdo a tus aspiraciones.</p>`,
            quote: 'Una meta sin un plan es solo un deseo. - Antoine de Saint-Exupéry',
            resume: `<h2>Indagando en tu laboratorio mental:</h2> <p>¿Por qué son importantes los <span class="keyword">objetivos</span> en la vida?</p><p>¿Cómo influyen los <span class="keyword">obstáculos y los desafíos</span> en la consecución de objetivos?</p><p>¿Qué tienes que hacer, cómo vas a encontrar el <span class="keyword">propósito de tu vida</span> y cuál es ese propósito?</p><h2>Enseñanzas sobre el establecimiento de metas:</h2><p>Las metas son la <span class="keyword">base de la existencia</span>, dan dirección y propósito.</p> <p>Definir metas claramente evita la <span class="keyword">dispersión de esfuerzos.</span></p> <p>Nuestra vida tiene un <span class="keyword">propósito</span> en servir a otros y contribuir.</p> <p>El <span class="keyword">éxito</span> es lograr metas sucesivas que acercan a la visión.</p><h2>Técnicas para el establecimiento de metas:</h2><p>Escribe metas claras, especificas, alineadas con lo que quieres en la vida y traza un <span class="keyword">plan especifico para lograrlas</span>.</p> <p>Desarrolla tu imaginación y <span class="keyword">visualiza</span> lo que quieres en la vida.</span> <p>Disciplinate a <span class="keyword">pagar</span> el precio por lo que quieres en la vida, las grandes cosas requieren un desbalance.</p> <p>Ve el capítulo 15 y 16 del <a class="post-link" href="https://www.youtube.com/watch?v=62wDYoPC4Sg&list=PLVCAyfXUAsByGdNHLdAU9HuuAuTY9gspS&ab_channel=JesusS%C3%A1nchez" target="_blank" rel="noopener" >seminario fénix</a> para que profundices sobre este tema</p> `
        },
        post2: {
            date: '28-Agosto-23',
            title: 'El Papel Vital de la Disciplina en tu Vida',
            img: 'disciplina-post2.png',
            id: '2',
            category: 'disciplina',
            content: `<p class="post-text"><span class="highlighted">Sin el control de la disciplina,</span> tu destino da un giro radical por el camino de la mediocridad.<span class="highlighted"> Imagina una vida confinada a las sombras, donde tus aspiraciones se convierten en polvo y tu potencial se desperdicia como un tesoro abandonado.</span> Imagina el dolor del arrepentimiento</span> al contemplar un rastro de proyectos inacabados, sueños abandonados y habilidades sin explotar. <span class="highlighted">Un tapiz tejido con hilos de procrastinación, ambiciones enredadas y promesas incumplidas.</span> <span class="highlighted">La mediocridad envuelve con sus brazos fríos e implacables</span> a quienes carecen de disciplina. <span class="highlighted">Tu potencial, que alguna vez fue un horno ardiente, se reduce a una vela.</span> La gloria que pudiste haber obtenido se desliza entre tus dedos como granos de arena, dejando solo amargura y anhelo por lo que pudo haber sido.</p>
            <p class="post-text"><span class="highlighted">El mundo recuerda a quienes tienen la audacia</span> de grabar sus nombres con actos de disciplina y perseverancia. <span class="highlighted">Recompensa a quienes reúnen el coraje para desafiar la comodidad y enfrentar la adversidad de frente.</span> Imagína el sabor de la amargura al ver a otros elevarse</span> a alturas que tú alguna vez aspiraste a alcanzar. <span class="highlighted">Tu falta de disciplina te condena a ser un espectador, aplaudiendo cortésmente a quienes se atrevieron a perseguir sus sueños mientras tú te quedabas atrás.</span></p>
            <p class="post-text"><span class="highlighted">Así que elige, amigo mío.</span> Acepta la disciplina ahora o soporta la agonía del arrepentimiento durante toda tu vida más tarde. <span class="highlighted">La disciplina demuestra que lo ordinario se convierte en extraordinario.</span> Sin la disciplina, no eres más que un barco a la deriva en el mar del potencial desperdiciado, destinado a los pasillos silenciosos de la mediocridad.</p>
            <p class="post-text" ><span class="highlighted">En la búsqueda de nuestras ambiciones y aspiraciones,</span> la disciplina emerge como una fuerza impulsora que nos impulsa hacia adelante, conduciéndonos implacablemente hacia el triunfo. <span class="highlighted">Sirve como base sobre la que se construyen nuestros logros, transformando los sueños en realidad.</span> La disciplina es mucho más que simplemente cumplir con tareas; es la esencia misma de alcanzar la grandeza personal.<span class="highlighted"> La disciplina es la habilidad de tomar decisiones consistentes con nuestros objetivos a pesar de las dificultades y distracciones que puedan surgir en nuestro camino</span>. Sin embargo, la disciplina no es un estado permanente, sino más bien una habilidad que puede ser fortalecida con el tiempo.<span class="highlighted">Imagina la disciplina como un músculo que podemos entrenar y fortalecer</span>. A medida que enfrentamos decisiones en la vida, ya sea grandes o pequeñas, <span class="highlighted">la disciplina juega un papel crucial al ayudarnos a tomar las elecciones que estén alineadas con nuestros objetivos y valores</span>. La disciplina nos permite resistir las tentaciones momentáneas y evaluar las consecuencias a largo plazo de nuestras acciones.</p>
            <p class="post-text"><span class="highlighted">La disciplina implica tomar acciones consistentes que nos acerquen a nuestros objetivos.</span> Es un compromiso constante de hacer lo que sabemos que es correcto, incluso cuando las tentaciones o los obstáculos sean desafiantes. La disciplina y las metas están relacionadas.</span> Sin metas bien definidas, la disciplina no tiene sentido. <span class="highlighted">Las <a href="#/disciplina/articulo/1" class="post-link">metas</a> iluminan nuestro camino y nos inspiran a mantenernos en el camino correcto.</span> La disciplina no siempre es fácil.</span> Requiere coraje para enfrentar lo desconocido y la fuerza de voluntad para mantener el rumbo incluso cuando se presentan obstáculos imprevistos.</p>
            <p class="post-text"><span class="highlighted">El compromiso es un componente vital de la disciplina.</span> Al comprometernos con nuestras metas, estamos estableciendo una base sólida para la acción constante y enfocada.<span class="highlighted"> Nuestra propia resistencia interna puede ser uno de los mayores obstáculos para la disciplina.</span> A menudo, nuestra mente busca la comodidad y la gratificación instantánea en lugar del trabajo duro y sostenido.<span class="highlighted"> La autodisciplina puede transformarse en un hábito arraigado.</span> Al realizar acciones disciplinadas de manera consistente, estamos cableando nuestra mente y nuestro comportamiento hacia la excelencia. <span class="highlighted">Los momentos de falta de motivación son inevitables.</span> Aquí es donde la disciplina se convierte en nuestra aliada más poderosa. <span class="highlighted">En lugar de depender únicamente de la motivación, confiamos en nuestros hábitos disciplinados para impulsarnos hacia adelante.</span> Yo no creo en la motivación, la motivación es para almas débiles, ya que quienes la abrazan, al primer obstáculo que tienen, suelen abandonar. En su lugar, la verdadera fuerza reside en la disciplina implacable que persiste en las condiciones más adversas.</p> `,
            quote: 'La disciplina es la llave maestra hacia la riqueza. -Brian Tracy',
            resume: `<h2>Indagando en tu laboratorio mental:</h2> <p>¿Qué medidas necesitas tomar para mantener el <span class="keyword">enfoque</span> en tus metas?.</p><p>¿Cuál es el logro más significativo que has experimentado gracias a la disciplina y qué <span class="keyword">aprendiste</span> de ese proceso?.</p>¿Cómo podrías <span class="keyword">fortalecer</span> tu resiliencia y autodisciplina para superar los desafíos que se te presentan?<p></p><h2>Enseñanzas sobre la Disciplina:</h2><p>Aquellos que desafían la comodidad y perseveran son recompensados.</p><p><span class="keyword">La disciplina</span> transforma lo ordinario en extraordinario.</p><p>El<span class="keyword">autodominio</span> y la <span class="keyword">resiliencia</span> son fundamentales para cultivarla.</p><h2>Técnicas para Fortalecer la Disciplina:</h2><p>Establecer <a href="#/disciplina/articulo/1" class="post-link">metas</a> claras proporciona dirección y propósito.</p><p>En lugar de imaginar todo lo que quieres, imagina escenarios en los que <span class="keyword">superas</span> con éxito los desafíos. Esto fortalecerá tu confianza y mentalidad positiva.</p><p> Ante los problemas, en lugar de quedarte enfocado en los obstáculos, concéntrate en las posibles soluciones. Esto promoverá una actitud <span class="keyword">proactiva</span>.</p><p><a href="#/" class="post-link">Planifica</a> tu día y tu semana en bloques dedicados a <span class="keyword">actividades específicas</span>. Esto te ayudará a mantener una estructura constante.</p>`
        }
    },
    productividad: {
    },
    mentalidad: {
        post1: {
            date: '',
            title: '',
            img: 'mentalidad-post1.png',
            id: '1',
            category: 'mentalidad',
            content: '',
            quote: '',
            resume: '',
        }
    },
    masculinidad: {
        post1: {
            date: '22-Septiembre-23',
            title: 'Más allá del placer inmediato',
            img: 'masculinidad-post1.png',
            id: '1',
            category: 'masculinidad',
            content: `<p class="post-text"> Desperdiciar <span class="highlighted">la energía más valiosa que tienes</span> te hace débil, todas <span class="highlighted">tus aspiraciones y ambiciones caen</span>, se debilita tu disciplina, esto fue lo que me paso a mí, <span class="highlighted">el éxito no espera a los débiles</span> que se dejan controlar por sus impulsos. Cualquier hombre que alcanzó el éxito es porque tiene un <span class="highlighted">total autocontrol y autodominio en sí</span> mismo, sabe como canalizar emociones hacia lo que quiere, sabe canalizar la emoción de la avaricia, de la envidia, del coraje y del sexo para conseguir lo que quiere. Este hombre <span class="highlighted">reconoce esas emociones</span> y lo que hace es entrar en el <span class="highlighted">campo de batalla</span>, reconocer a sus enemigos y jugar para destrozarlos. No puedes encontrar algún hombre que tenga éxito y que no tenga un <span class="highlighted">dominio sobre su mente</span>.  En mi caso lo que hice fue aceptar que soy un lujurioso y obtener consciencia del poder esta energía y usarla para concentrar todos mis esfuerzos para satisfacer a la mujer más hermosa del mundo y que ella esté orgullosa de mí, si algo <span class="highlighted">atrae a las mujeres</span> te puedo asegurar que es <span class="highlighted">tu capacidad y tu autocontrol para lograr cosas</span>. Me volví demasiado fuerte mentalmente, comprendí que esto es una distracción para lo que quiero, debes eliminar todas esas cosas que haces que te alejen de tus metas. Tal vez si tu objetivo es ser actor de contenido +18, este artículo no es para ti, hablando de contenido +18, yo <span class="highlighted">aborrezco el porno</span>, salí de esa adicción y no me arrepiento de hacerlo. Pero la masturbación se convirtió en mi verdugo. Cuando tiraba mi <span class="highlighted">energía al suelo</span> me sentía débil y vencido. Pero algo de lo que reconozco es que después de hacer esto me sentía terrible conmigo, pero ese sentimiento lo canalizaba para tener más fuerza en el gimnasio y funciono, recordaba que era un perdedor por hacerlo y eso me llevo a entrenar como nunca. </p>
            <p class="post-text"> El masturbarte <span class="highlighted">roba tu energía y tu concentración</span>(2 de los recursos más valiosos que podemos tener hoy en día). Pero puede que si tú no tienes <span class="highlighted">claridad mental </span> sobre lo que quieres en la vida lo sigas haciendo, ¿por qué? Porque probablemente no sea tu objetivo dejarlo o no lo estés <span class="highlighted">tomando en serio</span>, por lo menos este fue mi caso, veía videos del estilo: ”deja el porno", "deja de masturbarte” pero detrás de eso no había un <span class="highlighted">motivo válido</span> para no hacerlo, piénsalo, es como irte a dormir sin sueño, no tiene sentido porque no te vas a dormir, en cambio si supieras que tienes que dormir por una serie de <span class="highlighted">razones</span> te forzarías a apagar tu mente y a descansar. Así que necesitas encontrar un motivo válido para dejar de hacerlo. No vale decir: <span class="highlighted">“para ver que se siente”, “para ver cuanto aguanto”.</span> Cuando eyaculamos <span class="highlighted">liberamos la energía más poderosa del mundo</span>, ¿no me crees?. Te invito a leer e investigar sobre energía y vibración, te invito a leer <span class="highlighted">“Think and Grow Rich”</span> para que reflexiones sobre lo que hablo y decidas si quieres seguir tirando esa energía o usarla para conseguir cosas que tu mismo no te crees capaz de lograrlas.  </p>
            <p class="post-text"> Los gigantes de la industria como <span class="highlighted">Henry Ford, Thomas A. Edison, Elon Musk, Steve Jobs, Muhammad Ali, Nikola Tesla </span> no se la pasaron desperdiciando esta energía. La enfocaron en algo más productivo. <span class="highlighted">Crearon grandes cosas que cambiaron al mundo</span>. ¿Crees que Henry Ford se la pasaba con una mano en la polla imaginando fantasías sexuales mientras se daba placer para satisfacer? No, Henry Ford se la pasaba con las 2 manos creando inventos, <span class="highlighted">imaginando y visualizando el éxito</span> que estos tendrían y como se hacía jodidamente rico. Es muy extremo dejar de hacerlo y no te digo que sea fácil, pero las recompensas por dejar de hacerlo son incomparables, sin duda alguna vale la pena dejar de hacerlo. </p>
            <p class="post-text"> No te prometo que esto vaya a mejorar tu habilidad cognitiva, que te vaya a ser más atractivo o toda esa basura que escuchas por internet, <span class="highlighted"> te comparto por experiencia propia lo que he vivido al dejar este hábito</span>, mi fuerza de voluntad y autodisciplina se va a las nubes, <span class="highlighted">mi carácter se vuelve más serio y enfocado</span> hacia lo que quiero.  Esto <span class="highlighted">no es nada fácil</span>, vas a requerir unos tremendos 🥚🥚para dejarlo si es que es tu objetivo. Si decides dejar de ser <span class="highlighted">esclavo de este vicio</span> en hora buena te has vuelto libre. Ahora si estás leyendo esto y ayer te la jalaste no esperes a tener la energía muy elevada. Si has logrado <span class="highlighted">periodos largos de mas 1 o 2 semanas en retención seminal</span>, debes dirigir toda esa <span class="highlighted">energía</span> que se traduce en toda tu atención y esfuerzo hacía un objetivo. Solo mira a los que te rodean, están arruinados, se la pasan viendo porno y masturbándose su cuarto como ratas porque <span class="highlighted">no tienen la fortaleza mental</span> de construir un imperio. Pero no te culpo, precisamente el entorno nunca ayuda, al contrario. En un entorno tan sexualizado es difícil lograr esto, <span class="highlighted">debes cuidar tu atención</span> en la calle hacia las mujeres si te quieres apartar de esos pensamientos sexuales, si te llegan es normal, pero no es normal que los dejes en tu mente, los debes cambiar pensando solo en lo que quieres.  <span class="highlighted"> ¿Quieres impresionar a una mujer? Saca tu mejor versión</span> y construye cosas ambiciosas a base de sacrificio, disciplina y honor. No te fijes en ella, solo ponte a entrenar durísimo a estudiar como loco, a mejorar en tu trabajo o negocio, <span class="highlighted">trabaja más que nadie</span>. En la religión Judía y  Cristiana, el  <span class="highlighted">masturbarse es signo de pobreza mental y física </span>Steve Jobs conservaba su energía para producir y generar poder y riqueza.</p>            `,
            quote: 'Encuentra un león que no ha comido durante un tiempo y tendrás un gato peligroso. -Nelson Mandela',
            resume: `<h2>Indagando en tu laboratorio mental:</h2> <p>¿Quieres más <span class="keyword">ambición</span> por ser un mejor líder? </p> <p>¿Quieres mas <span class="keyword">desempeño</span>?</p>  <p>¿Por qué quieres dejar de masturbarte? ¿te quita <span class="keyword"> tiempo</span>? ¿es tu meta dejar de hacerlo? ¿quieres alcanzar grandes rachas? ¿quieres canalizar tu energía?</p> <h2>Enseñanzas:</h2> <p>Necesitas un <span class="keyword"> motivo valido </span> para dejar de hacerlo, sin una meta o propósito del porque quieres dejarlo, será imposible que lo dejes de hacer.</p> <p>El <span class="keyword">autocontrol y la canalización de la energía</span> son fundamentales para el éxito. Debes aprender a dirigir tus impulsos y emociones hacia metas productivas en lugar de desperdiciarlos. </p> <p> La masturbación y <span class="keyword">la pérdida de energía pueden afectar tu concentración</span> y fuerza de voluntad. Dejar este hábito puede aumentar tu autodisciplina y enfoque en tus objetivos. </p> <h2>Técnicas:</h2>  <p>Ya sea que estés en el gimnasio, en la calle o en algún otro lugar público, <span class="keyword">controla tu mirada</span> hacia las mujeres para desexualizar tu cerebro.  </p> <p>Si no quieres hacerlo, simple y sencillamente <span class="keyword">no lo hagas.</span></p>`
        }
    }
};
